version: "3.9"

networks:
  back-end:
    driver: "bridge"
  front-end:
    driver: "bridge"

volumes:
  db-data: {}

services:
  db:
    container_name: db-postgres
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nhtminh09032002@
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - back-end
    volumes:
      - db-data:/var/lib/postgresql/data

  # Container NodeJS
  server:
    container_name: nodejs
    build:
      context: ./backend_nest-js
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - back-end
    depends_on:
      - db
      - livekit

  # caddy:
  #   image: livekit/caddyl4
  #   command: run --config /etc/caddy.yaml --adapter yaml
  #   restart: unless-stopped
  #   network_mode: "host"
  #   volumes:
  #     - ./livekit/caddy.yaml:/etc/caddy.yaml
  #     - ./livekit/caddy_data:/data

  livekit:
    container_name: livekit
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    # network_mode: "host"
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    ports:
      - "7880:7880"
    networks:
      - back-end

  # redis:
  #   image: redis:6-alpine
  #   command: redis-server /etc/redis.conf
  #   network_mode: "host"
  #   volumes:
  #     - ./livekit/redis.conf:/etc/redis.conf
